# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:10-jessie

jobs:
  preparation:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}

      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: "."
          paths:
            - "node_modules"

  build:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .

      - run: yarn build
      - persist_to_workspace:
          root: "."
          paths:
            - "dist"
            - package.json
            - LICENSE
            - README.md

  test:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .

      - run: yarn test:ci
      - store_test_results:
          path: test-results


  publish:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}

      - run: npm publish




workflows:
  my-workflow:
    jobs:
      - preparation
      - build:
          requires:
            - test

      - test:
          requires:
            - preparation


      - publish:
          requires:
            - build

          filters:
            tags:
              only: /^v.*$/
            branches:
              ignore: /.*/
